title:       "Michaela Davis"
description: "Cybersecurity professional based in Toledo, Ohio."
url:         "https://md-helloworld.github.io"  # no trailing slash
baseurl:     "/index"

author:
  name:     "Michaela Davis"
  email:    "michaela.davis.oh@email.com"
  linkedin: "https://www.linkedin.com/michaeladavisoh"
  github:   "md-helloworld"

theme:      null
markdown:   kramdown   
permalink:  /blog/:title/

plugins:
  - jekyll-feed   
  - jekyll-seo-tag     

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore